export type StateDef = {
  code2: string; // "MD"
  name: string; // "Maryland"
  fredUnemp: string; // "MDUR"
  fredHpi: string; // "MDSTHPI" (All-Transactions HPI)
};

export const STATES: StateDef[] = [
  { code2: "AL", name: "Alabama", fredUnemp: "ALUR", fredHpi: "ALSTHPI" },
  { code2: "AK", name: "Alaska", fredUnemp: "AKUR", fredHpi: "AKSTHPI" },
  { code2: "AZ", name: "Arizona", fredUnemp: "AZUR", fredHpi: "AZSTHPI" },
  { code2: "AR", name: "Arkansas", fredUnemp: "ARUR", fredHpi: "ARSTHPI" },
  { code2: "CA", name: "California", fredUnemp: "CAUR", fredHpi: "CASTHPI" },
  { code2: "CO", name: "Colorado", fredUnemp: "COUR", fredHpi: "COSTHPI" },
  { code2: "CT", name: "Connecticut", fredUnemp: "CTUR", fredHpi: "CTSTHPI" },
  { code2: "DE", name: "Delaware", fredUnemp: "DEUR", fredHpi: "DESTHPI" },
  { code2: "DC", name: "District of Columbia", fredUnemp: "DCUR", fredHpi: "DCSTHPI" },
  { code2: "FL", name: "Florida", fredUnemp: "FLUR", fredHpi: "FLSTHPI" },
  { code2: "GA", name: "Georgia", fredUnemp: "GAUR", fredHpi: "GASTHPI" },
  { code2: "HI", name: "Hawaii", fredUnemp: "HIUR", fredHpi: "HISTHPI" },
  { code2: "ID", name: "Idaho", fredUnemp: "IDUR", fredHpi: "IDSTHPI" },
  { code2: "IL", name: "Illinois", fredUnemp: "ILUR", fredHpi: "ILSTHPI" },
  { code2: "IN", name: "Indiana", fredUnemp: "INUR", fredHpi: "INSTHPI" },
  { code2: "IA", name: "Iowa", fredUnemp: "IAUR", fredHpi: "IASTHPI" },
  { code2: "KS", name: "Kansas", fredUnemp: "KSUR", fredHpi: "KSSTHPI" },
  { code2: "KY", name: "Kentucky", fredUnemp: "KYUR", fredHpi: "KYSTHPI" },
  { code2: "LA", name: "Louisiana", fredUnemp: "LAUR", fredHpi: "LASTHPI" },
  { code2: "ME", name: "Maine", fredUnemp: "MEUR", fredHpi: "MESTHPI" },
  { code2: "MD", name: "Maryland", fredUnemp: "MDUR", fredHpi: "MDSTHPI" },
  { code2: "MA", name: "Massachusetts", fredUnemp: "MAUR", fredHpi: "MASTHPI" },
  { code2: "MI", name: "Michigan", fredUnemp: "MIUR", fredHpi: "MISTHPI" },
  { code2: "MN", name: "Minnesota", fredUnemp: "MNUR", fredHpi: "MNSTHPI" },
  { code2: "MS", name: "Mississippi", fredUnemp: "MSUR", fredHpi: "MSSTHPI" },
  { code2: "MO", name: "Missouri", fredUnemp: "MOUR", fredHpi: "MOSTHPI" },
  { code2: "MT", name: "Montana", fredUnemp: "MTUR", fredHpi: "MTSTHPI" },
  { code2: "NE", name: "Nebraska", fredUnemp: "NEUR", fredHpi: "NESTHPI" },
  { code2: "NV", name: "Nevada", fredUnemp: "NVUR", fredHpi: "NVSTHPI" },
  { code2: "NH", name: "New Hampshire", fredUnemp: "NHUR", fredHpi: "NHSTHPI" },
  { code2: "NJ", name: "New Jersey", fredUnemp: "NJUR", fredHpi: "NJSTHPI" },
  { code2: "NM", name: "New Mexico", fredUnemp: "NMUR", fredHpi: "NMSTHPI" },
  { code2: "NY", name: "New York", fredUnemp: "NYUR", fredHpi: "NYSTHPI" },
  { code2: "NC", name: "North Carolina", fredUnemp: "NCUR", fredHpi: "NCSTHPI" },
  { code2: "ND", name: "North Dakota", fredUnemp: "NDUR", fredHpi: "NDSTHPI" },
  { code2: "OH", name: "Ohio", fredUnemp: "OHUR", fredHpi: "OHSTHPI" },
  { code2: "OK", name: "Oklahoma", fredUnemp: "OKUR", fredHpi: "OKSTHPI" },
  { code2: "OR", name: "Oregon", fredUnemp: "ORUR", fredHpi: "ORSTHPI" },
  { code2: "PA", name: "Pennsylvania", fredUnemp: "PAUR", fredHpi: "PASTHPI" },
  { code2: "RI", name: "Rhode Island", fredUnemp: "RIUR", fredHpi: "RISTHPI" },
  { code2: "SC", name: "South Carolina", fredUnemp: "SCUR", fredHpi: "SCSTHPI" },
  { code2: "SD", name: "South Dakota", fredUnemp: "SDUR", fredHpi: "SDSTHPI" },
  { code2: "TN", name: "Tennessee", fredUnemp: "TNUR", fredHpi: "TNSTHPI" },
  { code2: "TX", name: "Texas", fredUnemp: "TXUR", fredHpi: "TXSTHPI" },
  { code2: "UT", name: "Utah", fredUnemp: "UTUR", fredHpi: "UTSTHPI" },
  { code2: "VT", name: "Vermont", fredUnemp: "VTUR", fredHpi: "VTSTHPI" },
  { code2: "VA", name: "Virginia", fredUnemp: "VAUR", fredHpi: "VASTHPI" },
  { code2: "WA", name: "Washington", fredUnemp: "WAUR", fredHpi: "WASTHPI" },
  { code2: "WV", name: "West Virginia", fredUnemp: "WVUR", fredHpi: "WVSTHPI" },
  { code2: "WI", name: "Wisconsin", fredUnemp: "WIUR", fredHpi: "WISTHPI" },
  { code2: "WY", name: "Wyoming", fredUnemp: "WYUR", fredHpi: "WYSTHPI" },
];